language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - /home/travis/.cargo
# But don't cache the cargo registry
before_cache:
  - rm -rf /home/travis/.cargo/registry

env: >
  DATABASE_URL=postgres://postgres:@localhost:5432/diesel_testing
  RUST_TEST_THREADS=1
  SCHEMA_REGISTRY_PASSWORD=silly_password

services:
  - postgresql
addons:
  postgresql: "9.6"

before_script:
  - which diesel || cargo install diesel_cli
  - rustup component add clippy
  - diesel setup
  - diesel migration run

script:
  - cargo test --verbose
  - cargo clippy
